---
- name: Set the ipv4_address variable to the value provided by a 'genesis' role if one is defined
  set_fact:
    ipv4_address: "{{ hostvars['127.0.0.1']['ipv4_address'] }}"
  when: hostvars['127.0.0.1']['ipv4_address'] is defined

- name: Set the ipv4_address variable to the default value if it doesn't already have one. The default is the value defined in the inventory file, which should be the IP address of the server that is being configured.
  set_fact:
    ipv4_address: "{{ inventory_hostname }}"
  when: ipv4_address is not defined

- name: Set the server_name variable to the value provided by a 'genesis' role if one is defined
  set_fact:
    server_name: "{{ hostvars['127.0.0.1']['server_name'] }}"
  when: hostvars['127.0.0.1']['server_name'] is defined

- name: Set the server_name variable to the default value if it doesn't already have one. The default is the value of the hostname retrieved from the server that is being configured.
  set_fact:
    server_name: "{{ ansible_hostname }}"
  when: server_name is not defined
