---
- name: Provision the EC2 Server
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - ./overrides.yml

  roles:
    # Taken from https://github.com/jlund/streisand
    - genesis-amazon

- include: cloud-status.yml
- include: mumble.yml
